# Generated by Django 4.2.5 on 2023-10-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.CharField(blank=True, max_length=30, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_creator', models.CharField(blank=True, max_length=30, null=True)),
                ('moderator', models.CharField(blank=True, max_length=30, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('date_formation', models.DateField(blank=True, null=True)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'sell_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id_request', models.OneToOneField(db_column='id_request', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bmstu_lab.sellrequest')),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.category')),
            ],
            options={
                'db_table': 'request_category',
                'managed': True,
                'unique_together': {('id_request', 'id_category')},
            },
        ),
    ]
