# Generated by Django 4.2.7 on 2024-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='sellrequest',
            old_name='id_creator',
            new_name='id_user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Пароль'),
        ),
    ]
