# Generated by Django 4.2.7 on 2024-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_API', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
