# Generated by Django 4.2.7 on 2024-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server_API', '0003_category_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='popularity',
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='status_priority',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
